gpu: "0"
multi_gpu: null
mgpus: False

model_name: PointConv

full: False

arch: PointConv
last_relu: False
allow_less_points: False

# general args
batch_size: 1
epochs: 860
learning_rate: 0.0001

optimizer: Adam
pretrain: pretrain_weights/PointConv_775_0.1118.pth #./experiment/PointConvFlyingthings3d-2019-11-05_12-58/checkpoints/PointConv_164_0.0842.pth PointConv_775_0.1118.pth
weight_decay: 0.0001

dim: 3
num_points: 8192

DEVICE: cuda

evaluate: False

dataset: KITTI 
data_root: /dataset

data_process:
  DEPTH_THRESHOLD: 35.
  NO_CORR: True

# data augmentation
aug_together:
  degree_range: 0.1745329252
  shift_range: 1.
  scale_low: 0.95
  scale_high: 1.05
  jitter_sigma: 0.01
  jitter_clip: 0.00

aug_pc2:
  degree_range: 0.
  shift_range: 0.3
  jitter_sigma: 0.01
  jitter_clip: 0.00

# miscalleneous
workers: 8

lag_big_radius: 1
kernel_shape: 1
layers: 1
is_training: True

#depth
pseudo_lidar: False
max_high: 1.0
DEPTH_LR: 0.0001
depth_ckpt: depth_network/models/checkpoint.pth.tar
train_with_eval: False
fix_bn: False







