gpu: "1"
multi_gpu: null

model_name: PointConv

Stereo: False
full: False

arch: PointConv
last_relu: False
allow_less_points: False

# general args
batch_size: 2
epochs: 1000
learning_rate: 0.0001

optimizer: Adam
pretrain: ./pretrain_weights/PointConv_140_0.1126.pth  #PointConv_775_0.1118.pth
weight_decay: 0.0002

dim: 3
num_points: 8192

DEVICE: cuda

evaluate: False

dataset: kitti
data_root: ../../dataset/data_odometry_color/sequences/02/Mono_depth  #  Stereo_pc Pesudo_GAnet

data_process:
  DEPTH_THRESHOLD: 35.
  NO_CORR: True

# data augmentation
aug_together:
  degree_range: 0.1745329252
  shift_range: 1.
  scale_low: 0.95
  scale_high: 1.05
  jitter_sigma: 0.01
  jitter_clip: 0.00

aug_pc2:
  degree_range: 0.
  shift_range: 0.3
  jitter_sigma: 0.01
  jitter_clip: 0.00

# miscalleneous
workers: 4








